gefParams:
  pid:
    epicServerUrl: http://pid.gwdg.de/handles/
    localPrefix: 11022
    user: 10+22
    pass:
  gefDocker:
    url: http://192.168.97.42:4142/api/
    timeout: 120000 # building docker images is slooow

# use the simple server factory, run on a single port
server:
  applicationContextPath: /gef
  type: simple
  connector:
    type: http
    port: 4042

# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: WARN
  # Logger-specific levels.
  loggers:
    eu.eudat.gef: INFO
#    eu.eudat.gef.rest.ReverseProxy: DEBUG

  appenders:
    - type: console

