# Base image: Minimal Alpine Linux image
FROM alpine:latest

MAINTAINER Alexandr Chernov <kstchernov@gmail.com>

LABEL "eudat.gef.service.name"="PID Downloader"
LABEL "eudat.gef.service.description"="Downloads a list of files provided by PIDs"
LABEL "eudat.gef.service.version"="0.1"

RUN mkdir /root/volume

#CMD ["/root/volume/downloader.sh"]
CMD ["ls"]