Vagrant.configure("2") do |config|
  config.vm.box = "ubuntutrusty"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.network :forwarded_port, guest: 4042, host: 4042

  # Irods
  config.vm.network :forwarded_port, guest: 1247, host: 1247
  # for i in 20000..20099
  #   config.vm.network :forwarded_port, guest: i, host: i
  # end

  config.vm.provision :shell, :path => "master.sh"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
end
