/**
 * Created by wqiu on 18/08/16.
 */
let actionTypes = {
    APIINFO_FETCH_SUCCESS: 'APIINFO_FETCH_SUCCESS',

    SERVICES_FETCH_START: 'SERVICES_FETCH_START',
    SERVICES_FETCH_SUCCESS: 'SERVICES_FETCH_SUCCESS',
    SERVICES_FETCH_ERROR: 'SERVICES_FETCH_ERROR',

    SERVICE_FETCH_START: 'SERVICE_FETCH_START',
    SERVICE_FETCH_SUCCESS: 'SERVICE_FETCH_SUCCESS',
    SERVICE_FETCH_ERROR: 'SERVICE_FETCH_ERROR',

    SERVICE_UPDATE_START: 'SERVICE_UPDATE_START',
    SERVICE_UPDATE_SUCCESS: 'SERVICE_UPDATE_SUCCESS',
    SERVICE_UPDATE_ERROR: 'SERVICE_UPDATE_ERROR',

    JOB_LIST_FETCH_START: 'JOB_LIST_FETCH_START',
    JOB_LIST_FETCH_SUCCESS: 'JOB_LIST_FETCH_SUCCESS',
    JOB_LIST_FETCH_ERROR: 'JOB_LIST_FETCH_ERROR',

    JOB_REMOVAL_START: 'JOB_REMOVAL_START',
    JOB_REMOVAL_SUCCESS: 'JOB_REMOVAL_SUCCESS',
    JOB_REMOVAL_ERROR: 'JOB_REMOVAL_ERROR',

    NEW_BUILD: 'NEW_BUILD',
    NEW_BUILD_ERROR:  'NEW_BUILD_ERROR',

    VOLUME_FETCH_START: 'VOLUME_FETCH_START',
    VOLUME_FETCH_SUCCESS: 'VOLUME_FETCH_SUCCESS',
    VOLUME_FETCH_ERROR: 'VOLUME_FETCH_ERROR',

    FILE_UPLOAD_START: 'FILE_UPLOAD_START',
    FILE_UPLOAD_SUCCESS: 'FILE_UPLOAD_SUCCESS',
    FILE_UPLOAD_ERROR: 'FILE_UPLOAD_ERROR',

    INSPECT_VOLUME_START: 'INSPECT_VOLUME_START',
    INSPECT_VOLUME_SUCCESS: 'INSPECT_VOLUME_SUCCESS',
    INSPECT_VOLUME_EMPTY: 'INSPECT_VOLUME_EMPTY',
    INSPECT_VOLUME_ERROR: 'INSPECT_VOLUME_ERROR',

    IO_ADD_START: 'IO_ADD_START',
    IO_ADD_SUCCESS: 'IO_ADD_SUCCESS',
    IO_ADD_ERROR: 'IO_ADD_ERROR',

    IO_REMOVE_START: 'IO_REMOVE_START',
    IO_REMOVE_SUCCESS: 'IO_REMOVE_SUCCESS',
    IO_REMOVE_ERROR: 'IO_REMOVE_ERROR',

    USER_FETCH_START: 'USER_FETCH_START',
    USER_FETCH_SUCCESS: 'USER_FETCH_SUCCESS',
    USER_FETCH_ERROR: 'USER_FETCH_ERROR',

    USER_TOKENS_FETCH_START: 'USER_TOKENS_FETCH_START',
    USER_TOKENS_FETCH_SUCCESS: 'USER_TOKENS_FETCH_SUCCESS',
    USER_TOKENS_FETCH_ERROR: 'USER_TOKENS_FETCH_ERROR',

    ROLES_FETCH_SUCCESS: 'ROLES_FETCH_SUCCESS',
    ROLES_FETCH_ERROR: 'ROLES_FETCH_ERROR',
    ROLE_USERS_FETCH_SUCCESS: 'ROLE_USERS_FETCH_SUCCESS',
    ROLE_USERS_FETCH_ERROR: 'ROLE_USERS_FETCH_ERROR',
};


export default actionTypes;
