FROM alpine:latest

MAINTAINER Alexandr Chernov <kstchernov@gmail.com>

LABEL "eudat.gef.service.name"="Copy to/from a volume"
LABEL "eudat.gef.service.description"="Copies files to/from a running container to a volume"
LABEL "eudat.gef.service.version"="0.1"

RUN mkdir /root/volume

CMD ["cp"]
