/**
 * Created by wqiu on 18/08/16.
 */
'use strict';

let actionTypes = {
    PAGE_CHANGE: 'PAGE_CHANGE',
    ERROR_OCCUR: 'ERROR_OCCUR',
    SERVICE_FETCH_START: 'SERVICE_FETCH_START',
    SERVICE_FETCH_SUCCESS: 'SERVICE_FETCH_SUCCESS',
    SERVICE_FETCH_ERROR: 'SERVICE_FETCH_ERROR',
    JOB_FETCH_START: 'JOB_FETCH_START',
    JOB_FETCH_SUCCESS: 'JOB_FETCH_SUCCESS',
    JOB_FETCH_ERROR: 'JOB_FETCH_ERROR',
    FILE_ADDED: 'FILE_ADDED',
    FILE_UPLOAD_START: 'FILE_UPLOAD_START',
    FILE_UPLOAD_ERROR: 'FILE_UPLOAD_ERROR',
    FILE_UPLOAD_SUCCESS: 'FILE_UPLOAD_SUCCESS'
};


export default actionTypes;

