Vagrant.configure("2") do |config|
  config.vm.box = "ubuntutrusty"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.network :forwarded_port, guest:  80, host: 6080
  config.vm.network :forwarded_port, guest: 443, host: 6443
  config.vm.network :forwarded_port, guest: 1247, host: 1247

  config.vm.provision :shell, :path => "irods.sh"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
end
