SOURCES := $(shell find . -iname '*.go')

build: volume-filelist

build-linux: volume-filelist-liux

volume-inspector-linux: $(SOURCES)
	$(GOPATH)/bin/golint ./...
	go vet ./...
    go build ./...
# install the bin
	GOOS=linux GOARCH=amd64 go install github.com/EUDAT-GEF/GEF/services/volume-filelist

volume-inspector: $(SOURCES)
	$(GOPATH)/bin/golint ./...
	go vet ./...
	go build ./...

# install the bin
	go install github.com/EUDAT-GEF/GEF/services/volume-filelist

clean:
	go clean
